// import React from 'react';
import BannerShort from '../components/banner-short';
import '../styles/about.scss'

function  About() {
  return (
    <div className='about'>
      <BannerShort title='Apropos de nous'/>
      <div className='sommary'>
        <h4>CE QU'IL  FAUT SAVOIR</h4>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi a quas, aperiam consectetur quia id deleniti iste accusantium, 
        repellendus harum earum suscipit doloremque non voluptas vel ipsam nobis ut nesciunt?
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloremque cum recusandae exercitationem, 
        nulla quis quos. Possimus iure quasi recusandae eligendi! Quisquam ex deleniti illo ducimus sapiente neque? 
        Pariatur rem cumque vitae nesciunt consectetur placeat dolores, explicabo dolorem consequatur voluptatibus molestias 
        reprehenderit nisi nihil sequi fugit id modi eum iste assumenda hic ullam ab incidunt. Totam facere ipsa sint ipsam ea suscipit voluptatem, 
        quasi unde adipisci pariatur quod saepe dolor sequi reiciendis minus alias nesciunt similique veritatis expedita. Dolorem necessitatibus voluptates,
        quidem praesentium vel facere ut reiciendis inventore voluptate ratione cum amet tempore delectus animi accusamus! Dolorem, exercitationem. 
        Dolorum odio quasi reprehenderit minus iusto soluta velit nostrum doloremque eaque at,
        esse expedita nesciunt maiores, quo commodi distinctio totam accusamus consequatur perferendis eum ipsam, facilis ducimus aut. Officiis vitae fugiat tempora id,
        voluptas nisi blanditiis expedita autem! Consequatur obcaecati voluptatibus ex velit minima numquam adipisci odit atque repudiandae cumque. Dolorem reprehenderit rerum culpa sapiente numquam pariatur optio,
        sit doloremque facilis quisquam animi enim, maxime tenetur tempore beatae at nulla veritatis! Necessitatibus unde error itaque recusandae quaerat vitae rem placeat assumenda officiis, ex dolore quasi soluta autem eveniet eius? 
        Tempore accusamus incidunt temporibus ab, quos beatae maiores ipsum vel, veritatis sequi, magnam culpa inventore quaerat! Molestiae laboriosam ea possimus iste illo expedita temporibus ratione eos, doloribus sequi asperiores repudiandae voluptas dolorem ad voluptates itaque natus laborum cum amet,
        reprehenderit aliquid fugiat eum blanditiis. Exercitationem, ut. Tempore voluptatum rem alias suscipit, tempora unde dolores consectetur nemo corporis soluta, est dicta commodi dolorem cum atque quo, recusandae eum neque incidunt error.
        Quo, error soluta accusamus quas dignissimos aperiam vitae perferendis eaque.
        Earum similique incidunt, quae nostrum voluptas ea! Architecto eum quod exercitationem voluptas officiis inventore illo non, nam magni blanditiis. Distinctio, vitae! Veniam aut, 
        soluta tempora perferendis delectus quam! Perspiciatis eius incidunt laudantium excepturi voluptatibus dolores dicta fugiat possimus unde recusandae! Sed inventore quisquam ipsam, 
        corrupti perferendis consequuntur delectus accusamus aperiam laborum eligendi totam enim aliquam nam facilis soluta iusto distinctio neque eaque. Itaque, eos id! Corrupti ad repudiandae amet inventore laudantium, 
        consequuntur quaerat temporibus excepturi velit iste ea optio sint debitis eius. Dicta possimus quidem molestiae deleniti molestias odit enim numquam quisquam porro beatae. Ut perspiciatis illo repellat incidunt esse vitae fugiat, voluptatem at quia officiis tempore architecto fugit, reiciendis reprehenderit eius. Sint, in dolor. Asperiores perferendis fuga odit, laboriosam in error nihil quas quidem. Incidunt, sit necessitatibus! Nisi provident maxime illum eveniet suscipit dolorum veritatis dicta. Sint officiis accusantium iure aspernatur nam sit libero at beatae sed nostrum totam voluptatem corporis sapiente necessitatibus, inventore id a dolore optio molestiae assumenda autem. Reprehenderit libero veniam repudiandae fugit voluptatum. Incidunt, maiores tempore facilis ducimus veniam dolore error minus vero nemo, culpa veritatis molestiae asperiores quis a quasi pariatur! Assumenda voluptatum itaque sit?
         Nisi ullam velit illo quasi officiis excepturi veniam rerum cupiditate reprehenderit omnis eos molestias est, quo asperiores saepe rem magnam incidunt consequatur iste assumenda vero cum vitae temporibus! Hic quae reprehenderit inventore labore magni modi ad maiores exercitationem ullam cum architecto optio aut, beatae nobis at aperiam, vero dolore. Minima optio officiis eligendi assumenda rerum temporibus obcaecati. Laboriosam nemo fugit quas repellendus quasi eius perferendis, adipisci vitae cupiditate reiciendis ea temporibus beatae dolor porro consectetur modi autem laborum voluptatibus dolore impedit deleniti tempore veniam? Eveniet saepe praesentium numquam, voluptatem consequatur unde quas, quidem impedit harum accusantium illum ea. Voluptate voluptates, est temporibus vel, sequi officiis veniam sapiente pariatur nesciunt aut in eaque aspernatur necessitatibus! Modi voluptates reprehenderit, maiores quisquam, vero officia optio repellat tenetur id quos dolore maxime non atque natus. Labore minus similique, totam aperiam ex itaque quia, est, ipsa veritatis iste consequuntur quaerat culpa omnis eligendi dolor aut beatae molestiae exercitationem unde? Ducimus dignissimos veniam officia cumque nobis est quasi qui deserunt iure saepe voluptas quisquam aut tenetur magni aspernatur, esse nesciunt dolorum earum. Voluptas, sit quo velit rem ut impedit eos quisquam neque enim pariatur nostrum sunt sequi ad officia id! Et voluptates quos delectus aspernatur! Dignissimos dicta architecto illo neque cum itaque eaque recusandae natus, ut atque assumenda tempore, aperiam error quisquam tempora eum sint repellendus harum, nam culpa libero ab perferendis quaerat rem! Eveniet porro doloremque consectetur! Illo, itaque minus eveniet accusantium voluptates quo praesentium error, adipisci ea, sint accusamus! Esse sit dolorem quidem quia, nobis laborum optio facere consectetur blanditiis nulla eius vel aperiam inventore voluptate ducimus, quis atque ipsa eligendi eaque ipsam. Vel saepe similique enim blanditiis porro voluptatibus ducimus, in illum nostrum harum placeat beatae culpa laudantium neque molestias voluptatum assumenda? Illum dolore doloribus amet et sunt, deleniti dicta eos nam sed ab iure, debitis consectetur atque quam, cupiditate fugit reiciendis. Fugit placeat quos deserunt sunt itaque necessitatibus ea rerum? Iusto nesciunt doloremque accusantium molestias sunt perspiciatis magnam, suscipit quos fuga modi nemo quo aliquam quisquam facilis laudantium eius! Vitae harum, et nobis iure dolorum, recusandae, voluptas voluptate totam omnis distinctio odit sed unde excepturi cupiditate provident id nisi! Quis veritatis, itaque ad eligendi quae amet architecto optio est laudantium odit corrupti beatae asperiores aperiam recusandae dolorem accusamus delectus nobis nam repellendus, dolores illum corporis neque error! Hic minima, adipisci provident porro ullam vero veritatis voluptas magnam impedit quod, cumque reprehenderit repudiandae.
        Illum dolore debitis id eos ea quae placeat, reiciendis delectus modi eligendi consequuntur a voluptatibus odit fugiat voluptas alias repellendus? Voluptate excepturi consectetur eaque, quos assumenda nobis necessitatibus maxime corrupti quam, deleniti vel quia. Laboriosam voluptates recusandae dolores, nobis vitae iusto aliquid incidunt officiis. Ut magnam repellat et quasi exercitationem dolorum. Eaque excepturi deserunt consequuntur autem quod, quae, voluptate dolore ipsa fugit commodi repellendus vel itaque quibusdam possimus corporis officia debitis vero nobis aliquid recusandae, in beatae. Excepturi inventore quaerat temporibus necessitatibus at, praesentium sit, eaque ex vero officia fuga saepe exercitationem nobis eum assumenda harum repellendus quasi corrupti, ab cupiditate! Iusto saepe quia, nostrum ex obcaecati architecto hic laudantium odio repellendus quaerat placeat autem commodi error, eligendi minima quis ducimus voluptates, dignissimos aliquid delectus repellat? Blanditiis alias saepe atque velit animi voluptates dolorem impedit odio. Hic perferendis cupiditate corrupti officiis illum neque.
      </div>
    </div>
  );
}

export default About;
